org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
VERSION=1.3.0
GROUP_NAME=com.qmdeve.vulkanblur
ARTIFACT_NAME=core
NAVIGATION_ARTIFACT_NAME=navigation
TRANSFORM_ARTIFACT_NAME=transform
DESCRIPTION=Android UI component library for real-time Vulkan Dual Kawase V2 blur surfaces and widgets
WEBSITE=https://blurview.qmdeve.com
